login:
    controller: 'jalismrs_authentication.controller.authentication_controller::index'
    methods: 'POST'
    path: '/login'
    
user:
    controller: 'jalismrs_authentication.controller.user_controller::index'
    methods: 'GET'
    path: '/user'
